// Optional development check. Set PLAYWRIGHT_MODULE to an existing Playwright module path,
// or install Playwright separately. The app itself has no Playwright dependency.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const baseUrl = process.env.CARWARS_BASE_URL || 'http://localhost:5173';
(async () => {
  fs.mkdirSync('tools/screenshots', { recursive: true });
  const browser = await chromium.launch({ headless: true, channel: 'msedge', args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.status() >= 400 && r.url().includes('localhost')) errors.push(`${r.status()} ${r.url()}`); });
  await page.goto(baseUrl);
  await page.waitForFunction(() => window.carLab?.modelReady);
  await page.waitForTimeout(1400);
  assert.equal((await page.evaluate(() => window.carLab.traffic())).length, 6, 'Six traffic cars should be active');
  assert.equal((await page.evaluate(() => window.carLab.telemetry())).damage, 0, 'A stationary car should remain undamaged');
  await page.screenshot({ path: 'tools/screenshots/desktop.png' });
  const idle = await page.evaluate(() => window.carLab.telemetry());
  await page.keyboard.down('KeyW'); await page.waitForTimeout(3000); await page.keyboard.up('KeyW');
  const drive = await page.evaluate(() => window.carLab.telemetry());
  assert.ok(drive.speed > 20, `Driving speed ${drive.speed}`);
  await page.keyboard.down('KeyW'); await page.keyboard.down('KeyD'); await page.waitForTimeout(2000);
  const turn = await page.evaluate(() => window.carLab.telemetry());
  await page.screenshot({ path: 'tools/screenshots/driving.png' });
  await page.keyboard.up('KeyW'); await page.keyboard.up('KeyD');
  assert.ok(Math.abs(turn.heading - drive.heading) > 0.15);
  await page.getByRole('button', { name: 'Заново' }).click(); await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Настройки физики' }).click();
  await page.locator('#grip').fill('0.65');
  assert.equal(await page.evaluate(() => window.carLab.tuning.grip), 0.65);
  await page.getByRole('button', { name: 'Вернуть базовую настройку' }).click();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.mouse.move(850, 350); await page.mouse.down(); await page.waitForTimeout(2600);
  assert.ok((await page.evaluate(() => window.carLab.telemetry())).speed < 0.1, 'First touch must be neutral');
  await page.mouse.move(830, 260, { steps: 6 }); await page.waitForTimeout(2000);
  const pointer = await page.evaluate(() => window.carLab.telemetry());
  const stick = await page.evaluate(() => window.carLab.joystick());
  assert.equal(stick.startX, 850); assert.equal(stick.startY, 350); assert.ok(stick.strength > 0.9);
  await page.screenshot({ path: 'tools/screenshots/joystick.png' });
  const speedBeforeRelease = (await page.evaluate(() => window.carLab.telemetry())).speed;
  await page.mouse.up();
  assert.ok(pointer.speed > 10, `Pointer speed ${pointer.speed}`);
  await page.waitForTimeout(1000);
  const released = await page.evaluate(() => window.carLab.telemetry());
  assert.ok(released.speed > speedBeforeRelease * 0.65 && released.speed < speedBeforeRelease, `Release inertia speed ${released.speed}`);
  await page.getByRole('button', { name: 'Заново' }).click(); await page.waitForTimeout(700);
  await page.mouse.move(1000, 650); await page.mouse.down();
  await page.mouse.move(989, 587, { steps: 6 }); await page.waitForTimeout(1000);
  assert.ok((await page.evaluate(() => window.carLab.telemetry())).signedSpeed > 5);
  await page.mouse.move(1011, 713, { steps: 8 }); await page.waitForTimeout(4000);
  const reversed = await page.evaluate(() => window.carLab.telemetry());
  assert.ok(reversed.signedSpeed < -1, `Reverse speed ${reversed.signedSpeed}`);
  assert.equal((await page.evaluate(() => window.carLab.joystick())).direction, -1);
  await page.mouse.move(989, 587, { steps: 8 }); await page.waitForTimeout(5000);
  const forwardAgain = await page.evaluate(() => window.carLab.telemetry());
  assert.ok(forwardAgain.signedSpeed > 5, `Forward again ${forwardAgain.signedSpeed}`);
  await page.mouse.up();
  // Only one software-rendered WebGL scene at a time avoids GPU contention in CI.
  await page.close();
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
  mobile.on('pageerror', e => errors.push(e.message));
  await mobile.goto(baseUrl); await mobile.waitForFunction(() => window.carLab?.modelReady);
  await mobile.waitForTimeout(1000); await mobile.screenshot({ path: 'tools/screenshots/mobile.png' });
  const session = await mobile.context().newCDPSession(mobile);
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 260, y: 300 }] });
  await mobile.waitForTimeout(800);
  assert.ok((await mobile.evaluate(() => window.carLab.telemetry())).speed < 0.1);
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 290, y: 245 }] });
  await mobile.waitForTimeout(2200);
  const touch = await mobile.evaluate(() => window.carLab.telemetry());
  const touchStick = await mobile.evaluate(() => window.carLab.joystick());
  assert.equal(touchStick.startX, 260); assert.equal(touchStick.startY, 300);
  await mobile.screenshot({ path: 'tools/screenshots/mobile-joystick.png' });
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  assert.ok(touch.speed > 5, `Touch speed ${touch.speed}`);
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ idle, drive, turn, pointer, stick, released, reversed, forwardAgain, touch, touchStick, errors }, null, 2));
  await browser.close();
})().catch(e => { console.error(e); process.exit(1); });

